#!/usr/bin/env ansible-playbook
---

- name: Set authorized keys for pi taken from github url
  authorized_key:
    user: pi
    state: present
    key: "https://github.com/{{ pwnagotchi_github_username }}.keys"

- name: Set authorized keys for root taken from github url
  authorized_key:
    user: root
    state: present
    key: "https://github.com/{{ pwnagotchi_github_username }}.keys"
