#!/usr/bin/env ansible-playbook
---

- apt:
      update_cache: yes
      upgrade: yes
- name: Upgrade all packages to the latest version
  apt:
      name: "*"
      state: latest
- name: Clean UnWanted Packages
  apt:
      autoremove: yes
      purge: yes
